[project]
name = "text2sql-w-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.52.0",
    "httpx>=0.28.1",
    "mcp[cli]>=1.9.1",
    "structlog>=25.3.0",
]
